parameters:
  buildConfiguration: "Release"

steps:
  - task: DotNetCoreCLI@2
    displayName: "Build the project - ${{ parameters.buildConfiguration }}"
    inputs:
      command: "build"
      arguments: "--no-restore --configuration ${{ parameters.buildConfiguration }}"
      projects: "**/*.csproj"

  - task: DotNetCoreCLI@2
    displayName: "Install .NET tools from local manifest - ${{ parameters.buildConfiguration }}"
    inputs:
      command: custom
      custom: tool
      arguments: "restore"

  - task: DotNetCoreCLI@2
    displayName: "Run unit tests - ${{ parameters.buildConfiguration }}"
    inputs:
      command: "test"
      arguments: "--no-build --configuration ${{ parameters.buildConfiguration }}"
      publishTestResults: true
      projects: "**/*.Tests.csproj"

  - task: DotNetCoreCLI@2
    displayName: "Create code coverage report - ${{ parameters.buildConfiguration }}"
    inputs:
      command: custom
      custom: tool
      arguments: "run reportgenerator -reports:$(Build.SourcesDirectory)/**/coverage.cobertura.xml -targetdir:$(Build.SourcesDirectory)/CodeCoverage -reporttypes:HtmlInline_AzurePipelines"

  - task: DotNetCoreCLI@2
    displayName: "Publish the project - ${{ parameters.buildConfiguration }}"
    inputs:
      command: "publish"
      projects: "**/*.csproj"
      publishWebProjects: false
      arguments: "--no-build --configuration ${{ parameters.buildConfiguration }} --output $(Build.ArtifactStagingDirectory)/${{ parameters.buildConfiguration }}"
      zipAfterPublish: true
